[package]
name = "griddb_rust"
version = "0.6.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
griddb-sys = { version = "5.0.0", path = "griddb-sys" }
chrono = "0.4"
convert_case = "^0.3.0"